### ISSUE TITLE
Twitter's Typeahead.js != old Bootstrap v2's typeahead

### ISSUE THREAD

**Issue by cvrebert** [kristopolous/articles#1]
> ## [Stylizing](http://getpostdelete.com/how-not-to-write-an-api.html)
> 
> You'd think that being explicitly referenced in the Bootstrap documentation as a supported library (in 2.3.2 but not 3.x<sup>1</sup>), typeahead.js would structure their HTML as a Bootstrap-friendly style drop-down…
> [...]
> 1. Where it changed from Bootstrap-typeahead to typeahead.js.

To dispel a key misconception here: The similarity of the names is indeed unfortunate & confusing, but [Twitter's Typeahead.js](https://github.com/twitter/typeahead.js) is completely separate from and has never shared any code with [Bootstrap v2's typeahead widget](http://getbootstrap.com/2.3.2/javascript.html#typeahead). I imagine that the fact that [old versions of Twitter's Typeahead.js offered optional Bootstrap integration](https://github.com/twitter/typeahead.js/tree/v0.9.0#bootstrap-integration) also contributed to this confusion.

In Bootstrap v3, Bootstrap's own typeahead widget from v2 was removed due to its complexity and its suffering from some significant bugs. The Bootstrap Core Team recommended that users migrate to Twitter's Typeahead.js since it was a superior alternative (see http://getbootstrap.com/migration/#notes), and since there was hope that Twitter's Typeahead.js would continue to offer an optional Bootstrap integration (which sadly didn't pan out).

With the release of version 3, Bootstrap ceased to be affiliated with Twitter (see https://github.com/twbs/bootstrap/issues/9899), which makes Typeahead.js's lack of integration/compatibility with Bootstrap more understandable.

**Comment by kristopolous** [comment]
I see. The internal politics and the fact this had to be clarified is fairly concerning.  Do you think most of users of bootstrap will presume the (now clarified to be incorrect) narrative that they are connected?

**Comment by cvrebert** [comment]
I think you might be overestimating the political factor. My (_unconfirmed, personal_) impression is that Typeahead.js is/was just low on manpower, and thus opted to expend their effort elsewhere rather than updating the Bootstrap integration, which would be nontrivial given how major the changes were between Bootstrap v2 & v3.

> Do you think most of users of bootstrap will presume the (now clarified to be incorrect) narrative that they are connected?

I think the likelihood for confusion is high, hence why I filed this issue.
So, would you mind updating the article so it doesn't further propagate the misinformation in question?

**Comment by kristopolous** [comment]
Sure ... I'll happily do so either tonight or tomorrow. Thanks

**Comment by kristopolous** [comment]
there you go.

**Comment by cvrebert** [comment]
Great, thanks!
